#!/bin/bash
##SBATCH -N 1
##SBATCH --job-name predict_peaks_paramscan
##SBATCH --tasks-per-node=1
##SBATCH --time=1-00:00:00
##SBATCH --mem=8G
##SBATCH -o predict_alphafold_peaks_paramscan.%j.log

### -------------------------------------------------------------------- ###
# Set the following parameters

# Environments and installation paths
repo_dir=/data1/groups/keatinglab/swans/savinovCollaboration/FragFold
conda_env_name=fragfold

# Inputs 
colabfold_data_csv= # path to csv generated by colabfold_process_output.py
experimental_data=$repo_dir/input/data/Savinov_2022_inhib_peptide_mapping.csv

### -------------------------------------------------------------------- ###

SECONDS=0

python $repo_dir/fragfold/predict_alphafold_peaks.py \
    --n_batches $LLSUB_SIZE \
    --batch_id $LLSUB_RANK \
    --colabfold_data_csv $1 \
    --verbose

ELAPSED="Elapsed: $(($SECONDS / 3600))hrs $((($SECONDS / 60) % 60))min $(($SECONDS % 60))sec"
echo $ELAPSED