#!/bin/bash
#SBATCH -N 1
#SBATCH --job-name predict_peaks
#SBATCH --tasks-per-node=1
#SBATCH --time=1-00:00:00
#SBATCH --mem=8G
#SBATCH -o predict_alphafold_peaks.%j.log

### -------------------------------------------------------------------- ###
# Set the following parameters

# Environments and installation paths
repo_dir=/data1/groups/keatinglab/swans/savinovCollaboration/FragFold
conda_env_name=fragfold

# Inputs 
colabfold_data_csv= # path to csv generated by colabfold_process_output.py
experimental_data=$repo_dir/input/data/Savinov_2022_inhib_peptide_mapping.csv

### -------------------------------------------------------------------- ###

SECONDS=0

conda run --no-capture-output -n $conda_env_name python $repo_dir/fragfold/predict_alphafold_peaks.py \
    --colabfold_data_csv $colabfold_data_csv \
    --n_contacts 3 \
    --n_weighted_contacts 3 \
    --iptm 0.3 \
    --contact_distance 0.4 \
    --cluster_peaks_frac_overlap 0.7 \
    --verbose

ELAPSED="Elapsed: $(($SECONDS / 3600))hrs $((($SECONDS / 60) % 60))min $(($SECONDS % 60))sec"
echo $ELAPSED